// Wine ingredient categories and options
export const wineIngredientCategories = {
  general: [
    'Grapes',
    'Sucrose',
    'Aleppo pine resin',
    'Caramel',
    'Concentrated grape must',
    'Grape must',
    'Rectified concentrated grape must',
    'Filling dosage',
    'Shipping dosage',
  ],
  gasesAndPackaging: [
    'Argon (E 938)',
    'Nitrogen (E 941)',
    'Carbon dioxide (E 290)',
    'Bottled in a protective atmosphere',
  ],
  acidityRegulators: [
    'Tartaric acid (E 334)',
    'Malic acid (E 296)',
    'Lactic acid (E 270)',
    'Calcium sulphate (E 516)',
    'Citric Acid (E 330)',
  ],
  stabilisingAgents: [
    'Citric Acid (E 330)',
    'Metatartaric acid (E 353)',
    'Gum arabic (E 414)',
    'Yeast mannoproteins',
    'Carboxymethylcellulose (E 466)',
    'Potassium polyaspartate (E 456)',
    'Fumaric acid (E 297)',
  ],
  preservativesAndAntioxidants: [
    'Potassium sorbate (E 202)',
    'Lysozyme (E 1105)',
    'L ascorbic acid (E 300)',
    'Dimethyldicarbonate (DMDC)',
    'Sulphites',
    'Sulfur dioxide',
    'Potassium bisulfite',
    'Potassium metabisulfite',
  ],
  processingAids: ['Egg', 'Milk'],
};

// Flatten all ingredients into a single array
export const allWineIngredients = [
  ...wineIngredientCategories.general,
  ...wineIngredientCategories.gasesAndPackaging,
  ...wineIngredientCategories.acidityRegulators,
  ...wineIngredientCategories.stabilisingAgents,
  ...wineIngredientCategories.preservativesAndAntioxidants,
  ...wineIngredientCategories.processingAids,
];

// Product field options
export const wineTypeOptions = [
  'Red',
  'White',
  'Rosé',
  'Sparkling',
  'Champagne',
  'Prosecco',
  'Port',
  'Sherry',
  'Dessert',
  'Fortified',
];

export const sugarContentOptions = [
  'Dry',
  'Semi-dry',
  'Semi-sweet',
  'Sweet',
  'Brut Nature',
  'Extra Brut',
  'Brut',
  'Extra Dry',
  'Sec',
  'Demi-Sec',
  'Doux',
];

export const packagingGasesOptions = [
  'Argon (E 938)',
  'Nitrogen (E 941)',
  'Carbon dioxide (E 290)',
  'Bottled in a protective atmosphere',
];

export const operatorTypeOptions = [
  'Producer',
  'Bottler',
  'Distributor',
  'Importer',
  'Exporter',
  'Wholesaler',
  'Retailer',
];

export const countryOptions = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahrain',
  'Bangladesh',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'San Marino',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];

export const netVolumeOptions = [
  '187ml',
  '250ml',
  '375ml',
  '500ml',
  '750ml',
  '1L',
  '1.5L',
  '3L',
  '5L',
  '6L',
];
